<a href="https://colab.research.google.com/github/ka5hely/MSSP-6070-Practical-Programming/blob/main/Modules/Week_04/PARTICIPATION_ACTIVITY_Week_4_Opening_a_CSV_file_and_modifying_the_contents.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
from google.colab import drive
drive.mount('/content/drive')

from google.colab import userdata
import os

github_token = userdata.get('GitHub')
owner = 'ka5hely' # Replace with the GitHub repository owner
repository = 'MSSP-6070-Practical-Programming' # Replace with the GitHub repository name

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
!git clone {clone_url}

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Cloning into 'MSSP-6070-Practical-Programming'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 145 (delta 57), reused 7 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (145/145), 1.24 MiB | 4.93 MiB/s, done.
Resolving deltas: 100% (57/57), done.
Changed directory to: /content/drive/My Drive/MSSP_607/WeeklyModules/Week_4/MSSP-6070-Practical-Programming/MSSP-6070-Practical-Programming

In [22]:
import pandas as pd
import os
os.chdir('/content/drive/MyDrive/MSSP_607/WeeklyModules/Week_4')

df = pd.read_csv('parsed.csv')
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California

In [28]:
# 2a. Find the 95th percentile of earthquake magnitude in Japan using magType of 'mb'
japan_mb_95th = df[
     (df['parsed_place'].str.endswith('Japan')) &
     (df['magType'] == 'mb')]['mag'].quantile(0.95)
print(f'The 95th percentile of earthquake magnitude in Japan is {japan_mb_95th}.')

The 95th percentile of earthquake magnitude in Japan is 4.9.

In [ ]:
# 2b. Find the percentage of earthquakes in Indonesia that were coupled with tsunamis.
indonesia_tsunami = df[(df['parsed_place'] == 'Indonesia') & (df['tsunami'] == 1)]
percentage_eq_ts = (indonesia_tsunami.shape[0])  / ((df[df['parsed_place'] == 'Indonesia']).shape[0])
print(f"The percentage of earthquakes in Indonesia that were coupled with tsunamis is {percentage_eq_ts * 100:.2f}%.")

The percentage of earthquakes in Indonesia that were coupled with tsunamis is 23.13%.

In [ ]:
# 2c. Get summary statistics for earthquakes in Nevada
df[df['parsed_place'] == 'Nevada'].describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [29]:
# 2d. Add a column to the dataframe indicating whether or not the earthquake happened in a country or US state that is on the Ring of Fire.
ring_of_fire_text = """Bolivia, Chile, Ecuador, Peru, Costa Rica, Guatemala, ^Mexico, Japan, Philippines, Indonesia, New Zealand, Antarctic, Canada, Fiji, Alaska, Washington, California, Russia, Taiwan, Tonga, Kermadec Islands"""
ring_of_fire = ring_of_fire_text.split(', ')
print(ring_of_fire)
df['ring_of_fire'] = df['parsed_place'].str.contains(r"|".join(ring_of_fire))
print(df[df['ring_of_fire']]['parsed_place'].unique()) #check if all countries are included
df[['ring_of_fire', 'parsed_place']]

['Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica', 'Guatemala', '^Mexico', 'Japan', 'Philippines', 'Indonesia', 'New Zealand', 'Antarctic', 'Canada', 'Fiji', 'Alaska', 'Washington', 'California', 'Russia', 'Taiwan', 'Tonga', 'Kermadec Islands']
['California' 'Alaska' 'Indonesia' 'Canada' 'Japan' 'Ecuador' 'Mexico'
 'Russia' 'Washington' 'Fiji' 'Chile' 'Peru' 'Guatemala'
 'Pacific-Antarctic Ridge' 'Taiwan' 'Tonga' 'Costa Rica' 'Philippines'
 'New Zealand' 'Bolivia' 'Western Indian-Antarctic Ridge'
 'Kermadec Islands']

      ring_of_fire parsed_place
0             True   California
1             True   California
2             True   California
3             True   California
4             True   California
...            ...          ...
9327          True   California
9328          True   California
9329         False  Puerto Rico
9330          True   California
9331          True   California

[9332 rows x 2 columns]

In [ ]:
# 2e. Calculate the number of earthquakes in the Ring of Fire locations and the number outside of them
rof_earthquakes = df['ring_of_fire'].value_counts()
print(rof_earthquakes)

ring_of_fire
True     7188
False    2144
Name: count, dtype: int64

In [ ]:
# 2f. Find the tsunami count along the Ring of Fire.
rof_tsnamis = df[(df['ring_of_fire'] == True) & (df['tsunami'] == 1)]
print(f"The tsunami count along the Ring of Fire is {rof_tsnamis.shape[0]}.")

The tsunami count along the Ring of Fire is 45.