<a href="https://colab.research.google.com/github/ka5hely/MSSP-6070-Practical-Programming/blob/main/Modules/Week_06/PARTICIPATION_ACTIVITY_Week_6_Write_a_lamda_function_for_a_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

from google.colab import userdata
import os

github_token = userdata.get('GitHub')
owner = 'ka5hely'
repository = 'MSSP-6070-Practical-Programming'

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'


!git clone {clone_url}

os.chdir("/content/drive/MyDrive/MSSP607/Modules/Week_06")
print(f"Changed directory to: {os.getcwd()}")

Mounted at /content/drive
Cloning into 'MSSP-6070-Practical-Programming'...
remote: Enumerating objects: 205, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 205 (delta 71), reused 36 (delta 36), pack-reused 114 (from 3)
Receiving objects: 100% (205/205), 1.55 MiB | 8.26 MiB/s, done.
Resolving deltas: 100% (81/81), done.
Changed directory to: /content/drive/MyDrive/MSSP607/Modules/Week_06

In [ ]:
import pandas as pd

df = pd.read_csv("Student Performance Data.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [ ]:
# I want write a lambda function which takes the df
# and return the students who didn't take test preparation course
# yet still got an above-average total score

no_prep_above_average = lambda df: df[
    (df['test preparation course'] == 'none') &
    (df['total score'] > df['total score'].mean())
]

print(no_prep_above_average(df))

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
2,female,group B,master's degree,standard,90,95,93,278,none,high
4,male,group C,some college,standard,76,78,75,229,none,high
5,female,group B,associate's degree,standard,71,83,78,232,none,high
12,female,group B,high school,standard,65,81,73,219,none,medium
...,...,...,...,...,...,...,...,...,...,...
981,male,group D,some high school,standard,81,78,78,237,none,high
984,female,group C,some high school,standard,74,75,82,231,none,high
992,female,group D,associate's degree,free/reduced,55,76,76,207,none,medium
993,female,group D,bachelor's degree,free/reduced,62,72,74,208,none,medium
999,female,group D,some college,free/reduced,77,86,86,249,none,high